### PR TITLE
Optimize some code, use newer material icons

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update Android Studio 4.0.1 -> 4.0.2
- Update gradle wrapper to 6.6.1 using git bash

### 2nd commit
- Fix a few deprecations

### 3rd commit (check the changelogs)
- material-dialogs 0.8.6.0 -> 0.8.6.2
- ExoPlayer 2.11.4 -> 2.12.0 (unfortunately bloats APK by around 300KB)
- Conscrypt 2.5.0 -> 2.5.1
- Okhttp 3.12.11 -> 3.12.12

### 4th commit
- Use ContextCompat.getSystemService, which uses the newer way automatically on API 23 and up

### 5th commit
- Miscellaneous cleanup

### 6th commit
- Remove a bunch of unused resources

### 7th commit
- Use the latest material icons
- Convert PNGs to drawable (reduces APK size by around 100KB)

### 8th commit
- Optimize remaining PNGs with https://ezgif.com/optipng/

I've built an APK and tested (on a Note 9 running Android 10), and everything works as it is supposed to. Here are APKs to test if you want them.
[Twire.zip](https://github.com/twireapp/Twire/files/5398699/Twire.zip)

### CODE REVIEW

**Comment by RickyM7** [comment]
Tested on a Redmi Note 4 (Snapdragon 625 - Miui 11 - Android 7.0). Everything seems to work fine.

**Comment by TacoTheDank** [comment]
Redid on top of newest commits.

**Comment by TacoTheDank** [comment]
@RickyM7 I generated new APKs for this rebase (attached where they were previously). Would you mind testing to see if everything still works fine on your device?

**Comment by TacoTheDank** [comment]
@samfundev Mind taking a look at this? :)

**Comment by RickyM7** [comment]
@TacoTheDank Of course, is this "Twire.zip" attached to the PR?

**Comment by TacoTheDank** [comment]
@RickyM7 Yeppers 👍

**Comment by RickyM7** [comment]
I tested it and again everything works perfectly.  I tested without logging in but I don't think it makes much difference.

**Comment by samfundev** [comment]
@TacoTheDank Thanks for the optimizations, appreciate it. The only thing I noticed is that in the 8th commit `ic_launcher-web.png` became a bit bigger. Not super important but you could fix that up before I pull this in.

**Comment by TacoTheDank** [comment]
@samfundev 👍

**Comment by samfundev** [comment]
Thanks for the PR!

**Pull request merged**
