### PR TITLE
Add Proxy to bypass Advertisements and Pink waiting Screen [WIP]

### PR DESCRIPTION
**Pull request by Nickwasused**
# About the Proxy ttv.lol (https://ttv.lol/)

They have extensions for Firefox and Chrome here:
https://github.com/TTV-LOL/extensions

Self Hosting will be possible: TTV-LOL/extensions#1 (comment)

The Privacy Policy can be found here: https://addons.mozilla.org/en-US/firefox/addon/ttv-lol/privacy/

# How does the ttv.lol work:
See here: https://github.com/saucettv/WorkingTwitchAdBlockers#m3u8-proxies

# This Pull request is fixing:
https://github.com/twireapp/Twire/issues/183
https://github.com/twireapp/Twire/issues/216

# The main focus of this Pull Request:
since there are no ads on Twire (at least for me) I want to fix the Pink Screen (see below) telling me to wait 30 Seconds

### Preview Apk:
- There Should be an APK built automatically below this Pull-Request

# Testing:

- is done with the Preview Apk over the Span of one week. (15.05.2021 to 22.05.2021)
- Testing is done on the Samsung Galaxy Tab SM-T510 with Android 10
- How do I notice when the API is getting used: there should be no ADs

### Test Result:

- There are small problems with ads getting through from time to time.
  - 1 Ad in about 4 Hours
  - The API developers are still working to improve AD blocking.
  - On some days I got no ADs
- The Problem with the Pink screen is gone. I never had one in the testing period.
- **Vods have no ADs blocked**

# Possible Problems:

- The received .m3u8 file is not using the best servers for your location (e.g. if you are in Germany you are not going to use german servers)
- Example I am from Germany and I get French servers (See **CLUSTER="fra06"** below):
```
#EXTM3U
#EXT-X-TWITCH-INFO:NODE="video-edge-18e68c.fra06",MANIFEST-NODE-TYPE="weaver_cluster",MANIFEST-NODE="video-weaver.arn03",SUPPRESS="true",SERVER-TIME="1621155573.89",TRANSCODESTACK="2017TranscodeX264_V2",USER-IP="127.0.0.1",SERVING-ID="*********************", CLUSTER="fra06",ABS="false",VIDEO-SESSION-ID="2508823718899679179",BROADCAST-ID="42066506348",STREAM-TIME="148197.894582",B="false",USER-COUNTRY="RU",MANIFEST-CLUSTER="arn03",ORIGIN="lhr05"
```

# How it works:
- first, there is a ping test send to ```https://customapi.adress/on```
- if the ping is not successful then the default twitch API will be used with the default code
- if the ping is successful then the custom API will be used for getting the initial .m3u8 file
- the code is based on this: 
  - https://github.com/TTV-LOL/extensions/blob/main/firefox/js/background.js
  - https://github.com/arthurbolsoni/Purple-adblock/blob/main/firefox/js/background.js

# Opt-in

- The Video Proxy is disabled by default
- The Default Video Url is set to "https://api.ttv.lol"
  - This is the Default URL of Purple-adblock
- You can set a custom Url but the API should be based on ttv.lol

# Revert to ttv.lol on 15.09.2021
I reverted back to ttv.lol, because of this:
Discord_mnfuOr3dSk

# to-do

- [ ] Wait until the Server code is public
- [x] Add Button to disable Proxy
- [x] Add Option for custom Proxy Url

### CODE REVIEW

**Comment by Perflyst** [comment]
I really don't like this proxy solution, especially since it is not (yet) open sourced. It might be nice for some alternative frontend for Twitch like Invidious, Nitter, etc but for an app for Twitch, like NewPipe for YouTube, I don't like such a solution.

Do you have more information about this "location where twitch doesn't run ads"?

**Comment by Nickwasused** [comment]
So it seems like there are only a few countries where Twitch can`t run ads. I don`t know the reason why there are no ads in these countries.

Countries I know without ads:
- Russia
- India

Source:
https://github.com/TTV-LOL/extensions/issues/12#issue-898414606


ttv.lol is using Russian servers as seen here:
```
#EXTM3U
#EXT-X-TWITCH-INFO:NODE="video-edge-18e68c.fra06",MANIFEST-NODE-TYPE="weaver_cluster",MANIFEST-NODE="video-weaver.arn03",SUPPRESS="true",SERVER-TIME="1621155573.89",TRANSCODESTACK="2017TranscodeX264_V2",USER-IP="127.0.0.1",SERVING-ID="*****************************",CLUSTER="fra06",ABS="false",VIDEO-SESSION-ID="2508823718899679179",BROADCAST-ID="42066506348",STREAM-TIME="148197.894582",B="false",USER-COUNTRY="RU",MANIFEST-CLUSTER="arn03",ORIGIN="lhr05"
```
**COUNTRY="RU"**

**Comment by roshavagarga** [comment]
@Nickwasused @Perflyst While Twitch can run ads in other countries, some of them do not get any. I have never, while using uBlock Origin (default) on a browser, gotten an advertisement in Bulgaria, minus 1 time about 5+ years ago, when I got a political ad, once.

Have you looked into what projects like Streamlink do? They have an option that disables embedded ads, in some form or manner.

**Comment by Nickwasused** [comment]
Streamlink is filtering the HLS segments (maybe  I don`t know?)
See here: https://github.com/streamlink/streamlink/blob/534d9843a1ff6bf21d0ae849d8d3b4b587536bd7/src/streamlink/plugins/twitch.py#L38

I look into this implementation and try to get it working with twire. But this is far more difficult than using the Proxy method.

**Comment by roshavagarga** [comment]
Opt-in should be the way to go - as a user I'd prefer that at least.

**Comment by Nickwasused** [comment]
I have added Options for the Proxy in the Stream Player settings.

- The Video Proxy is disabled by default
- The Default Video Url is set to "https://api.ttv.lol"
- You can set a custom Url but the API should be based on ttv.lol

**Comment by Perflyst** [comment]
@samfundev do you have time to review the PRs from @Nickwasused? If not, are you okay with granting @Nickwasused permissions to this repository? Of course, only if @Nickwasused actually wants to have permission and (maybe) continue the project.

**Comment by peepopoggers** [comment]
Yeah as @Perflyst it may be a good idea to expand the development team if the creators aren't as active. This seems like a great project so maintaining it should be a priority and I think you should put thought into maintainers. It was done over at FreeTube and the rate of progress has increased several times over so I hope you will think on it.

**Comment by Perflyst** [comment]
@Nickwasused are you interested in write access?

**Comment by Sokoloft** [comment]
Hello,

I built the "try-ttv.lol" branch and it seems that its using the old twitch API? I'm unsure, but the issue is that Twire displays nothing and gives some oops twitch servers can't be found error at the bottom of the app. 

The developer of luminous-ttv made an update for their project so that it handles proxy requests similar to how ttv.lol does. I was hoping to try this with twire. 

I'm not very familiar with how github works. I know a little. However has video proxy support been merged to Twires master branch? If so I'll build that with android studio. 

Thanks.

**Comment by Nickwasused** [comment]
Closed see: https://github.com/twireapp/Twire/discussions/407

**Pull request closed without merging**
