### PR TITLE
Update (spanish) strings.xml

### PR DESCRIPTION
**Pull request by fabiopolancoe**

### CODE REVIEW

**Review by Perflyst — APPROVED** [review]

**Comment by samfundev** [comment]
@fabiopolancoe Thanks for helping translate Twire! In the future, do you think you could translate using [Weblate](https://hosted.weblate.org/engage/twire/)? I'd like to manage the translations in one place so it would be great if you could translate using Weblate.

**Comment by fabiopolancoe** [comment]
@samfundev Yeah, it would be awesome, I really like Twire and it's nice to help. Will you keep uploading next releases to F-Droid?

**Comment by samfundev** [comment]
@fabiopolancoe Yep, I'll be uploading releases to F-Droid. I've been busy recently so I haven't had time to make a new release but it's definitely something I want to get done.

**Comment by fabiopolancoe** [comment]
No problem. I'm translating some strings on Weblate to test, and it works nice, I'll keep working on it ;D

**Comment by fabiopolancoe** [comment]
Okay, uhmmm. I think I actually corrected all marked errors and missing translations, but I'll keep checking for grammar errors.

**Pull request merged**
