### PR TITLE
Helix improvements

### PR DESCRIPTION
**Pull request by samfundev**
- Migrated some code that used offsets to use cursors instead.
- Converted the search page to use helix API.
- Reduced the number of API calls that were being made.
- Fix VOD chat since video IDs no longer start with a "v".
- Migrate video progress to no longer have the "v".

### CODE REVIEW

**Comment by Nickwasused** [comment]
I tested it and Twire is crashing while fetching/setting the total Stream Count.

```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.perflyst.twire.debug, PID: 24357
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.perflyst.twire.adapters.MainActivityAdapter.getItemCount()' on a null object reference
        at com.perflyst.twire.fragments.NavigationDrawerFragment.showAndSetStreamCount(NavigationDrawerFragment.java:126)
        at com.perflyst.twire.fragments.NavigationDrawerFragment.lambda$fetchAndSetOnlineSteamsCount$0$com-perflyst-twire-fragments-NavigationDrawerFragment(NavigationDrawerFragment.java:114)
        at com.perflyst.twire.fragments.NavigationDrawerFragment$$ExternalSyntheticLambda4.TaskFinished(Unknown Source:2)
        at com.perflyst.twire.tasks.GetStreamsCountTask.onPostExecute(GetStreamsCountTask.java:74)
        at com.perflyst.twire.tasks.GetStreamsCountTask.onPostExecute(GetStreamsCountTask.java:22)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by samfundev** [comment]
@Nickwasused Uh, I'm not sure why that's happening. There's no code at NavigationDrawerFragment.java:126?
image

**Comment by Nickwasused** [comment]
@samfundev I fixed the problem, apparently, Android Studio had a problem (maybe caching or something.) So I removed the local Project and cloned it again. Now everything is working fine and stable.

**Review by Nickwasused — APPROVED** [review]

**Comment by Nickwasused** [comment]
It´s crashing while trying to play a Stream.
```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.perflyst.twire.debug, PID: 14366
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.perflyst.twire.debug/com.perflyst.twire.activities.stream.LiveStreamActivity}: java.lang.RuntimeException: bad array lengths
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: bad array lengths
        at android.os.Parcel.readString16Array(Parcel.java:1487)
        at android.os.Parcel.readStringArray(Parcel.java:1408)
        at com.perflyst.twire.model.UserInfo$1.createFromParcel(UserInfo.java:14)
        at com.perflyst.twire.model.UserInfo$1.createFromParcel(UserInfo.java:20)
        at com.perflyst.twire.model.UserInfo$1.createFromParcel(UserInfo.java:9)
        at android.os.Parcel.readParcelable(Parcel.java:3279)
        at android.os.Parcel.readValue(Parcel.java:3174)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getParcelable(Bundle.java:1001)
        at android.content.Intent.getParcelableExtra(Intent.java:8276)
        at com.perflyst.twire.activities.stream.LiveStreamActivity.getStreamArguments(LiveStreamActivity.java:59)
        at com.perflyst.twire.activities.stream.StreamActivity.onCreate(StreamActivity.java:86)
        at com.perflyst.twire.activities.stream.LiveStreamActivity.onCreate(LiveStreamActivity.java:73)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)```

**Review by Nickwasused — APPROVED** [review]
Everything is working now.

**Pull request merged**
